### ISSUE TITLE
Welcome to Support & Get Involved Menu items redundant

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#218]
I noticed in the new theme we have a new link in the subnav titled "Welcome to support" which was originally a bucket on the forum homepage. The content you see first when navigating to those pages is very similar.

I feel like we can remove "Get Involved" as the "Welcome to Support" references it in its content.

**Page**

![Image](https://github.com/WordPress/wordpress.org/assets/1657336/ca196a55-1898-4e46-9040-48285866c216)

| [Welcome to Support](https://wordpress.org/support/welcome/) | [Get Involved](https://make.wordpress.org/support/handbook/) | 
| --- | --- |
| ![Image](https://github.com/WordPress/wordpress.org/assets/1657336/a87db9d8-3b66-41b5-b331-4e7a38283101) |  ![Image](https://github.com/WordPress/wordpress.org/assets/1657336/f537ec23-b60a-4282-80b0-8665a3cf029f) |

**Comment by adamwoodnz** [comment]
I think this needs consideration. [Last time we removed the Get Involved link it was controversial](https://wordpress.slack.com/archives/C04U953K77A/p1694555656016189), and I think the link in the Welcome page is fairly buried and not obvious. @ndiego thoughts? Since you and I were involved last time.

**Comment by ryelle** [comment]
Slightly related to https://github.com/WordPress/wordpress.org/issues/236 — the Rosetta sites don't have pages for Guidelines or Welcome to Support, so those go to 404s. Get Involved is the only link that actually works since it's for an English make handbook.

**Comment by ndiego** [comment]
The "Get Involved" link was updated recently I think. It no longer goes to the main handbook page and instead goes to the [Contributing to the WordPress Forums](https://make.wordpress.org/support/handbook/contributing-to-the-wordpress-forums/), which is more appropriate IMO. Therefore, I think we should keep both links in the local Nav. 

> the Rosetta sites don't have pages for Guidelines or Welcome to Support, so those go to 404s. Get Involved is the only link that actually works since it's for an English make handbook.

For Rosetta sites, can we just hide links that are not relevant?

**Comment by adamwoodnz** [comment]
> The "Get Involved" link was updated recently I think. It no longer goes to the main handbook page and instead goes to the [Contributing to the WordPress Forums](https://make.wordpress.org/support/handbook/contributing-to-the-wordpress-forums/), which is more appropriate IMO. Therefore, I think we should keep both links in the local Nav.

In that case I'll close this. I've added a potential solution for Rosetta sites on #236
