### ISSUE TITLE
Change `wporg-ratings` star colors once new themes are launched

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#222]
> Star colors are defined inline in the `wporg-ratings` plugin and some rules use `!important` so can't be overridden. We can override all of it except the new review form. Once we've launched the new Themes and Plugins themes we can make the changes properly in the plugin. 

 _Originally posted by @adamwoodnz in [#211](https://github.com/WordPress/wordpress.org/issues/211#issuecomment-2038863410)_

**Comment by ndiego** [comment]
@adamwoodnz @StevenDufresne [given the feedback](https://wordpress.slack.com/archives/C04U953K77A/p1712763297539609?thread_ts=1712717222.251569&cid=C04U953K77A) so far on the Forums launch, it would be nice to update the star rating colors before the Plugins refresh is launched.  

The current suggestion is to use the pomegranate color (second from left), which was one of the colors @jasmussen proposed. 

![tests](https://github.com/WordPress/wordpress.org/assets/4832319/a05ac43f-1497-456d-bd32-966ac34f8da6)

**Comment by StevenDufresne** [comment]
I feel like star ratings, albeit a finer UI detail, typically play a role in communicating brand. While Pomegranate `#E26F56` is part of .org's official [color palette](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=101%3A4244&mode=dev), I haven't seen it show up consistently across any of the newer .org designs.

If we decide to use it here, we should be committed to also using it more often as our primary accent color.

**Comment by jasmussen** [comment]
> If we decide to use it here, we should be committed to also using it more often as our primary accent color.

That's definitely the intent.
