### ISSUE TITLE
Support forums: Pages in local navigation don't exist on Rosetta sites

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordpress.org#236]
See https://github.com/WordPress/wporg-main-2022/issues/430 — someone was looking for the German "Guidelines" page, but the link 404s. The local nav has local links to "Guidelines" and "Welcome to Support", but these don't exist on Rosetta sites.

<img width="482" alt="Screenshot 2024-04-09 at 1 26 23 PM" src="https://github.com/WordPress/wordpress.org/assets/541093/750c2965-8175-4e75-b505-d6fe6397aa0a">

The English pages are just pages, so it's not translatable content at the moment. Maybe these pages should also have a sync-to-patterns process?

**Comment by ndiego** [comment]
This was also reported in [Slack](https://wordpress.slack.com/archives/C04U953K77A/p1712998465094799):

> I'm checking the Spanish forums, and I cannot find a way to link to the proper URL for the menu (Guidelines, Welcome to Support...). In the Spanish sites we have different URL's for that:
> 
> Guidelines
> LINK (404) https://es.wordpress.org/support/guidelines/
> Real one: https://es.wordpress.org/support/instrucciones/
> 
> Welcome to Support
> LINK (404) https://es.wordpress.org/support/welcome/
> Real one: https://es.wordpress.org/support/bienvenida/
> 
> Get Involved
> LINK (English): https://make.wordpress.org/support/handbook/contributing-to-the-wordpress-forums/
> Real one: https://es.wordpress.org/support/manual-de-soporte/
> 
> Shouldn't that be a Menu / Block or something similar so we can edit that?

How can we all Rosetta sites to update these links?

**Comment by adamwoodnz** [comment]
As some sites already have their own pages, we could allow them to configure a `navigation` menu with local pages linked. 

![Image](https://github.com/WordPress/wordpress.org/assets/1017872/27c3be2f-b016-4e86-a48d-51fec2922691)

![Image](https://github.com/WordPress/wordpress.org/assets/1017872/9db29c53-dd1f-44cd-8ef0-06c42d218119)

Obviously admins could add more links than we'd like to this, so we could look at only taking the first 3?

PR up for review: https://github.com/WordPress/wordpress.org/pull/250

**Comment by ndiego** [comment]
Thanks @adamwoodnz, I added a comment on https://github.com/WordPress/wordpress.org/pull/250
