### ISSUE TITLE
Support forums redesign: Icons in table header not aligned

### ISSUE THREAD

**Issue by dionysous** [WordPress/wordpress.org#239]
Hi @ndiego , I think the redesign is great. However, I have noticed that the icons in the table headers are not centered in relation to the underlying content. I have a suggestion how to solve this within the CSS.

![icon-alignmenrt1](https://github.com/WordPress/wordpress.org/assets/12687777/ff56fd52-d339-4e57-aa99-54838509d62f)

![icon-alignmenrt2](https://github.com/WordPress/wordpress.org/assets/12687777/c6b7fd09-6d45-4810-b2fb-8e0169ea18c4)

## Solution:

1. Change this from 
https://github.com/WordPress/wordpress.org/blob/ca74bd12c4c9b0ae6070caab437dc9a725852993/wordpress.org/public_html/wp-content/themes/pub/wporg-support-2024/style.css#L3173
```.bbpress .forum-titles .bbp-topic-voice-count,
.bbpress .forum-titles .bbp-topic-reply-count {
	overflow: hidden;
}
```
to this
```.bbpress .forum-titles .bbp-topic-voice-count,
.bbpress .forum-titles .bbp-topic-reply-count {
	font-size: 0;
	color: transparent;
}
```

2. Replace this line `margin-right: 100px;`
https://github.com/WordPress/wordpress.org/blob/ca74bd12c4c9b0ae6070caab437dc9a725852993/wordpress.org/public_html/wp-content/themes/pub/wporg-support-2024/style.css#L3180 with this
`color: var(--wp--preset--color--charcoal-1);`

3. Remove this `margin-left: 20px;`
https://github.com/WordPress/wordpress.org/blob/ca74bd12c4c9b0ae6070caab437dc9a725852993/wordpress.org/public_html/wp-content/themes/pub/wporg-support-2024/style.css#L3188

**Comment by ndiego** [comment]
Thanks for logging this @dionysous! Looks like @adamwoodnz is on it.

**Comment by adamwoodnz** [comment]
Thanks for raising! The [design](https://www.figma.com/file/3eK690rwPubLvTEvJIJKRO/Forums?type=design&node-id=902%3A1413&mode=dev) actually replaces the icons with text, and we have an [issue](https://github.com/WordPress/wordpress.org/issues/243) for that.
