### ISSUE TITLE
Plugins: Videos in plugin readmes are no longer responsive

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#259]
Videos in plugin readmes are no longer responsive and "break out" of the container. You can see this in action on [this page](https://wordpress.org/plugins/block-visibility/). 

| New Design | Current Design |
|-|-|
|<img width="860" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/25154a2a-a990-478b-9d11-609998c4b16a">|<img width="864" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/5edd3918-d171-48d5-b27b-77544e29e716">|

**Comment by ryelle** [comment]
Looks like the iframe is missing a max-width — it's probably good to add that into the parent theme so this doesn't happen elsewhere.
