### ISSUE TITLE
Plugins: Add search bar to Developer Information and My Favorites pages

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#271]
In https://github.com/WordPress/wordpress.org/issues/252, we have discussed adding back internal search on single plugin pages. I overlooked the fact that we should probably also add it to the [Developer Information](https://test.wordpress.org/plugins/developers/) and [My Favorites ](https://test.wordpress.org/plugins/browse/favorites/)pages to maintain feature parity with the current site. 

In the proposed screenshots, I added a bit of extra space between the search bar and the content.

#### Developer Information

| Current | Proposed |
|-|-|
|<img width="1520" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/269be957-6dd1-4971-98eb-4d117d612c19">|<img width="1520" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/3bf87d65-b9e3-4f53-a233-1ffe76401c70">|

#### My Favorites 

| Current | Proposed |
|-|-|
|<img width="1520" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/860f414d-f5c3-43a8-af6d-0def73ea53d2">|<img width="1517" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/e36901c0-32fe-4a2c-ad76-879b48924fdd">|

cc @WordPress/meta-design

**Comment by StevenDufresne** [comment]
Added in:
- https://meta.trac.wordpress.org/changeset/13583
- https://meta.trac.wordpress.org/changeset/13584
