### ISSUE TITLE
Plugins: Standardize `<li>` margin for unordered and ordered lists

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#273]
I just noticed that there is different styling for list elements in ordered and unordered lists in plugin descriptions. Unordered list elements have an extra `8px` bottom margin. The extra margin makes the content feel very spaced out. 

| Ordered list ([example](https://test.wordpress.org/plugins/block-visibility/)) | Unordered list ([example](https://test.wordpress.org/plugins/create-block-theme/)) |
|-|-|
|<img width="507" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/41d170f8-2fc8-4cef-b235-bfdf54087c9d">|<img width="536" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/4fa7bf6b-4ae4-437f-bba8-684e4c00de37">|

It looks like this treatment is the same as the current theme but is much more pronounced with the new font and the fact that the line-height is `24px` on the current theme and `30px` on the new theme. I recommend we reduce the margin applied to unordered lists or remove it. 

| Current theme | New theme |
|-|-|
|<img width="1015" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/333f22e1-f472-482d-a8e6-ac54beca9256">|<img width="1230" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/6ca126d2-1402-491c-9352-c93258442f31">|

cc @WordPress/meta-design

**Comment by jasmussen** [comment]
Agreed, these should be the same. 

While we're here, the spacing between these buttons could be a bit better:

![Screenshot 2024-04-23 at 08 27 53](https://github.com/WordPress/wordpress.org/assets/1204802/847f1520-0e47-4576-9b1b-c7ee6524302c)

It appears that's only spaced by whitespace (` `). This would fix it up:

```
.plugin-actions {
    display: flex;
    gap: 16px;
}
```

16px feels a good rule of thumb for buttons in a row.
![Screenshot 2024-04-23 at 08 30 15](https://github.com/WordPress/wordpress.org/assets/1204802/7671872f-c663-4b9c-9d4a-cce7de441708)

**Comment by StevenDufresne** [comment]
> While we're here, the spacing between these buttons could be a bit better:

@jasmussen, please open new tickets to track unrelated changes for historical context.

**Comment by jasmussen** [comment]
[Done](https://github.com/WordPress/wordpress.org/issues/280)! Thanks.

**Comment by StevenDufresne** [comment]
I removed the bottom margin. As mentioned, the new theme has a better line-height and this is probably not needed anymore.
