### ISSUE TITLE
Plugins: Language Localization for YouTube Embeds

### ISSUE THREAD

**Issue by chriscct7** [WordPress/wordpress.org#275]
For some reason on the new test site for Plugins if a plugin uses a YouTube embed, the language for it seems to be forced German. An example of this is seen on Elementor's page:

![image](https://github.com/WordPress/wordpress.org/assets/1324637/e9b38b9e-b96d-4871-91a9-ca0fcef56c62)

**Comment by chriscct7** [comment]
And as soon as I post it I realize why:

`<html lang="de">`

**Comment by dd32** [comment]
This is because the test site is an untranslated german site; It'll be in the correct locale once launched to all sites.
