### ISSUE TITLE
Plugins: Improve spacing between Download / Live Preview buttons.

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wordpress.org#280]
Extracting from https://github.com/WordPress/wordpress.org/issues/273#issuecomment-2073511896:

The spacing between these buttons could be a bit better:

![Screenshot 2024-04-23 at 08 27 53](https://github.com/WordPress/wordpress.org/assets/1204802/847f1520-0e47-4576-9b1b-c7ee6524302c)

It appears that's only spaced by whitespace (` `). This would fix it up:

```
.plugin-actions {
    display: flex;
    gap: 16px;
}
```

16px feels a good rule of thumb for buttons in a row.
![Screenshot 2024-04-23 at 08 30 15](https://github.com/WordPress/wordpress.org/assets/1204802/7671872f-c663-4b9c-9d4a-cce7de441708)

**Comment by StevenDufresne** [comment]
Updated in https://meta.trac.wordpress.org/changeset/13591.
