### ISSUE TITLE
Plugins 2024 Theme: No hover state on Support Forum button

### ISSUE THREAD

**Issue by mathetos** [WordPress/wordpress.org#282]
One the single plugin page, the "View Support Forum" button does not have a hover state at all. 
![no-hover-state-support-forum](https://github.com/WordPress/wordpress.org/assets/930724/c2f3e129-705d-4dbb-b267-7518ed85abe0)

The "Download" button gets a darker blue background effect, I feel that's probably a little too subtle, but it's better than no hover effect at all.

**Comment by StevenDufresne** [comment]
I have a local PR that changes it to a link as agreed upon in [this ticket](https://github.com/WordPress/wordpress.org/issues/263#issuecomment-2068320567). Would that work for you? If you have any counterpoints to why this should stay a button please add them to that ticket! I'll close this one as it's already reported.
