### ISSUE TITLE
Plugins 2024 Theme: Screenshot thumbnails disappear

### ISSUE THREAD

**Issue by mathetos** [WordPress/wordpress.org#283]
When scrolling through the screenshot carousel, the thumbnails scroll too and eventually get hidden completely. That behavior doesn't exist on the current site. 

![screenshot-thumbnails-disappear](https://github.com/WordPress/wordpress.org/assets/930724/a11280c4-a54c-4c3b-bcda-b604c7cf6c62)

**Comment by StevenDufresne** [comment]
Do you mind sharing your browser and operating system details?

I'm not able to reproduce on the same plugin with the following browser/OS combinations:

MacOS / Chrome:v.124.0.6367.78
MacOS / Firefox:v.125.0.2
MacOS / Safari:v.17.2.1 

Windows 11/ Edge:v.122
Windows 11/ Edge:v.latest

**Comment by ndiego** [comment]
Yeah, I am not able to replicate either in the latest versions of Chrome or Safari. 🤔

**Comment by mathetos** [comment]
Now that everything is live, I can't replicate either, so I'll close. Thanks all!
