### ISSUE TITLE
Tighten up plugin cards

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#285]
Reported by: @jasmussen
<hr>

We can tighten up the plugin card a little bit. Here’s how it looks:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/e0146f44-2580-4bdd-b69a-07c17c09430a)

The heading and rating feels off in alignment, the icons at the bottom are top aligned, and the density is a a little too loose. Here’s how we could tighten that up a bit:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/f360a0e3-0bb6-44ff-a051-51d20c149107)

[Figma](https://href.li/?https://www.figma.com/file/IlEkGQqizcofzu8sfwW0Ff/WP.org-Plugins%27-LP-explorations?type=design&node-id=187%3A2713&mode=design&t=qFmzxzr1Fv1zUldc-1)) for metrics. The spacing between elements is 20px, like the padding. The header area unit is vertically centered, as are the individual icons at the bottom.

Number of reviews vs. rating stars can be entirely separate, but the font size and color (charcoal 4) can be tweaked. The bottom two items are also charcoal 4.

**Comment by StevenDufresne** [comment]
@jasmussen Is the logo intentionally back to `100px`? It's currently `80px`.

**Comment by jasmussen** [comment]
It's intentionally 100px, yes. That's not quite as big as 128 on the current site, but also large enough to afford a bit more harmonious of a heading line-height for 2-line plugin names as shown. 

But it's not the end of the world, we can do 80px as well if you've a strong instinct for that. Then we should remove the gap between ratings and title though.

<img width="762" alt="Suggestion" src="https://github.com/WordPress/wordpress.org/assets/1204802/9d3b1532-37ca-40c7-bb10-eb96064faf0e">

**Comment by StevenDufresne** [comment]
I would prefer a smaller icon as we have agreed, for now, that the [plugin name is most important for discoverability](https://meta.trac.wordpress.org/ticket/7577) and the real estate in the tile is already at a premium.

In terms of the spacing of the author container relative to the bottom of the description for the plugin in the design... based on the current excerpt limit, we need to accommodate 1-3 lines of text at full desktop width. The description length is variable but we maintain a consistent visual tile grid. This means that the space between the author and the bottom of the description varies depending on the excerpt length as the author container is always positioned at the bottom of the card. I wanted to mention that as I don't feel we need to change that. Feel free to push back.

Lastly, these designs have a modified star format; that change should be logged in a new ticket as it should have knock-on effect on other pages. I'm going to update it to match the color you provided though. 👍 

Would that satisfy the requirements of this ticket?

**Comment by jasmussen** [comment]
I think there's a chance to come back to these bits, but yes seems fine to go this route. This ticket exists as history we can always revisit.
