### ISSUE TITLE
Improve appearance of tabbar and support link

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#288]
Reported by: @jasmussen

<hr>

In this tab-bar, the support link stands out a bit:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/d84c7ab3-e115-4475-a43b-3bf84b6c83c2)

Can we:

* Use 16px font size for tabs and support link
* Remove the icon
* Text-align it so it lines up with the text inside the tabs
* Use the same font size as the text in the tabs, and underline it

**Comment by StevenDufresne** [comment]
@jasmussen 

Can you clarify this instruction:
- Text-align it so it lines up with the text inside the tabs
- Use the same font size as the text in the tabs, and underline it

Are you expecting something like this?

![Image](https://github.com/WordPress/wordpress.org/assets/1657336/c5a22477-39f9-48b8-91eb-0473bb2a4fe5)

**Comment by jasmussen** [comment]
> Are you expected something like this?

Yes, exactly that, except you can keep the Support link blueberry in color.

**Comment by StevenDufresne** [comment]
This becomes the only underlined link that's not part of the content. Do we plan to underline all the links?

<img width="400" alt="Screenshot 2024-05-01 at 3 47 37 PM" src="https://github.com/WordPress/wordpress.org/assets/1657336/e1741733-5d6d-4189-83c9-c8100292327e">

**Comment by jasmussen** [comment]
I think so, yes, and I believe that was one of the suggestions from a separate issue.
