### ISSUE TITLE
Forums: Comment field no longer spans width of container

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#289]
The comment input field should span the width of the container. I just noticed this today, but this issue was not present during the refresh launch, so perhaps a recent update caused it 🤔

<img width="1130" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/74ea094c-c028-4546-8342-59d8dae1b652">

**Comment by adamwoodnz** [comment]
I noticed it's also overflowing on mobile, causing horizontal scroll.

**Comment by adamwoodnz** [comment]
I've discovered that there were new styles added for Gutenberg 17.9: https://github.com/Automattic/blocks-everywhere/pull/201, probably before the Forums launch, as the width is set to the old forums width of 620px.

[Issue](https://github.com/Automattic/blocks-everywhere/issues/207) raised, I'll add a hotfix.
