### ISSUE TITLE
Plugins: Consider showing the language bar only on the landing page

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wordpress.org#293]
In other sections of the site, the language bar is shown only on the landing page. Here, it's also on subpages:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/4a1502e9-ca42-47fa-91e8-33d86e862224)

Should we omit this language-bar from subpages?

**Comment by ryelle** [comment]
There was also a conversation [about this in slack](https://wordpress.slack.com/archives/C04U953K77A/p1714467181419539). After the redesign, it was hard to find the banner, it stood out more in the old theme.

Good to keep in mind: "this little thingy is our best recruitment tool for Polyglots' team"

It also seems to be showing the generic banner for all plugins, when it should show different content for each plugin (depending on translation status), including a call to help out translating.

> Should we omit this language-bar from subpages?

Given the above, I don't think so. Once the contextual text is back it will make sense on single plugin pages. As for other archive pages, it does link to the correct (current) archive query on the locale site, so I'm inclined to leave it there too, in case people land on, for example, `/plugins/tags/backup/` from a google search.

**Comment by jasmussen** [comment]
Sounds good, it's considered then and this'll be in the archive to reopen and point to if it comes up. Thanks.
