### ISSUE TITLE
Plugins: Plugin page > Ratings > "See all" should omit the chevron

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wordpress.org#296]
If you go to a plugin page, e.g. [this one](https://test.wordpress.org/plugins/cool-timeline/), there's a chevron next to the see all link next to ratings:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/8b1e3f92-1302-4797-ad05-c6577a9a74fd)

That should be the same style as the "See all" link on the landing page:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/7ef8dc48-d20b-4e66-8219-27927efb759c)

**Comment by StevenDufresne** [comment]
Done in https://meta.trac.wordpress.org/changeset/13682
