### ISSUE TITLE
Plugin Directory: Committers can no longer be removed after design refresh

### ISSUE THREAD

**Issue by obenland** [WordPress/wordpress.org#299]
I tried removing a committer from a plugin today, [using the UI in the /advanced tab](https://developer.wordpress.org/plugins/wordpress-org/special-user-roles-capabilities/#committer) but was unable to do so.

Clicking the Delete button did not garner a response.

**Comment by StevenDufresne** [comment]
I'll take a look. Thanks.

**Comment by StevenDufresne** [comment]
@obenland This should be fixed now. Can you confirm?

**Comment by obenland** [comment]
Confirmed, thank you!
