### ISSUE TITLE
Plugins: Add more visible language switch indicator.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#301]
As mentioned by @tobifjellner in[ this slack](https://wordpress.slack.com/archives/C04U953K77A/p1714467181419539) thread, the language switcher is an important mechanism for onboarding new translators. 

The new theme reduces the visibility of the component by moving its position up and updating its style to match the rest of the site. 

# Proposal
We could give it the same treatment that we give the newest release on the developer.wp.org site:
- Larger font size
- Background color `#fffdd6`
- More Padding

### Screenshot
| Current | Proposal |
|--------|--------|
| <img width="1092" alt="Screenshot 2024-05-01 at 11 06 19 AM" src="https://github.com/WordPress/wordpress.org/assets/1657336/f60f16af-6923-43cf-a4a6-55f4e1ae8022"> | <img width="889" alt="Screenshot 2024-05-01 at 11 08 35 AM" src="https://github.com/WordPress/wordpress.org/assets/1657336/de110c17-994e-448d-bc02-78ba0dab26db"> | 

## [developer.wp.org](https://developer.wordpress.org/)

<img width="400" alt="Screenshot 2024-05-01 at 11 09 45 AM" src="https://github.com/WordPress/wordpress.org/assets/1657336/d6a024b2-3d69-4ae8-b2fd-818c5b626def">

**Comment by webdados** [comment]
It also seems that the link to help translating is gone, and it should be brought back.

**Comment by StevenDufresne** [comment]
@webdados 

> It also seems that the link to help translating is gone, and it should be brought back.

Did you verify that today? That should have already been fixed.

<img width="1213" alt="Screenshot 2024-05-01 at 6 51 52 PM" src="https://github.com/WordPress/wordpress.org/assets/1657336/d228d1f8-bfa9-4831-b0e2-539523090f94">

**Comment by webdados** [comment]
> @webdados
> 
> > It also seems that the link to help translating is gone, and it should be brought back.
> 
> Did you verify that today? That should have already been fixed.
> 

Yes, it's fixed now.

**Comment by fcoveram** [comment]
I agree that light blueberry is more used than light lemon. It also seems your proposal adds top and bottom padding. If that is the case, I'm fine with the suggestion.
