### ISSUE TITLE
Plugins: Proposal to refine plugin search bar layout

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#309]
This issue stems from the discussions in https://github.com/WordPress/wordpress.org/issues/252. While a more comprehensive and holistic solution for search/filtering across WordPress.org is needed, in the interim, I think we can make some changes to Plugins that will make searching from the Homepage easier and more visible.

I also think we can compress the design slightly on search and category archive pages by placing the search bar and the filters in a single row.  

### Homepage

| Current | Proposal 1 | Proposal 2 |
|-|-|-|
|<img width="1550" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/a1200449-028f-4258-a94f-52da34684091">|<img width="1550" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/15f11573-1c8d-4484-8695-b28993a606d4">|<img width="1549" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/9b7c9087-feba-4e97-9470-77a2e8609ce7">|

### Search + Category Archives

| Current | Proposed |
|-|-|
|<img width="1549" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/0a732bef-ca9c-42f6-90c4-bad463ff0974">|<img width="1550" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/dfd485a0-c615-4b34-af7e-d51b30368df0">|

cc @WordPress/meta-design

**Comment by mathetos** [comment]
I feel like Proposal 2 is the best use of space and visually leads the eye to the right places. But it's missing the contrast that makes search more obvious like Proposal 1 had. What if you added a light gray behind that "sub-header" area? 

This is quick and dirty and not the right colors for the search bar and category buttons, but something like this:
<img width="1203" alt="image" src="https://github.com/WordPress/wordpress.org/assets/930724/4218c34c-cf2e-418a-bb8d-febf172e9a5a">

**Comment by jasmussen** [comment]
I'd avoid introducing a gray shape behind the middle area, mainly because I'd expect the landing page itself to evolve and improve as a future iteration, and based on broader feedback on this first light refresh. To that end, I'd veer a version of Proposal 1, but keeping the tabs on the left:

![Screenshot 2024-05-07 at 16 26 33](https://github.com/WordPress/wordpress.org/assets/1204802/cb90581e-f40c-41c8-8136-340b8751b28b)

This would be mainly to give prominence to search on the landing page, and it would be not too far from the same header unit design that people were used to with the previous version.

**Comment by fcoveram** [comment]
I agree with @jasmussen about not adding a new area just for search and browsing actions, but I disagree with adding it in the hero section.

That area was thought to convey section identity and highlight content in an appealing manner. Showcase and News are palpable examples of that purpose. Therefore, I will keep it above the content area until we revisit the search and browse pattern of the site.

In terms of layout, I like the buttons on the right side. They behave like filters. Changing the category does not reset the search query.

**Comment by ndiego** [comment]
> That area was thought to convey section identity and highlight content in an appealing manner. Showcase and News are palpable examples of that purpose. Therefore, I will keep it above the content area until we revisit the search and browse pattern of the site.
> 
> In terms of layout, I like the buttons on the right side. They behave like filters. Changing the category does not reset the search query.

@fcoveram Does this mean you like "Proposal 2" above?

**Comment by jasmussen** [comment]
Part of the conversation may be about the visibility of the search field on the landing page, where the gray background intentionally makes it secondary. The darker background context gives this more contrast. 

Edit: not a strong opinion.

**Comment by StevenDufresne** [comment]
Since it seems like we're leaning toward aligned on the right, I'll mention that @dd32 is currently looking into result filtering and we'd have to do something like this based on that alignment:

![Group 1 (13)](https://github.com/WordPress/wordpress.org/assets/1657336/5cc2de2a-619a-43e2-8ac6-5301de4c323f)

**Comment by fcoveram** [comment]
> @fcoveram Does this mean you like "Proposal 2" above?

Yes @ndiego Sorry for not being clear 😅

**Comment by ndiego** [comment]
> Yes @ndiego Sorry for not being clear 😅

Cool. I think Proposal 2 would be a good iterative step (albeit a small one) and then we can assess how users are interacting with the search.

**Comment by StevenDufresne** [comment]
Alright, I'll move the categories to the right of the search bar.

**Comment by StevenDufresne** [comment]
I've updated the layout in [870fd28](https://github.com/WordPress/wordpress.org/commit/870fd28b77586f8ccfeaaf5eed1407a4f05a94bb). Reopen this issue if I've missed anything. Thanks all!
