### ISSUE TITLE
Plugin directory: Sentence case for secondary navigation items

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wordpress.org#318]
Related to https://github.com/WordPress/wporg-theme-directory/issues/55

We should standardize on sentence case for navigation items across secondary navigation. 

In the case of the plugin directory, it relates to these items:

![Image](https://github.com/WordPress/wporg-mu-plugins/assets/1204802/8944741e-61a6-4c70-a8fe-b690d7143ee6)

They should be updated to say:

* My favorites
* Submit a plugin (already okay)

**Comment by jasmussen** [comment]
@ryelle apologies, I believe I opened this issue in the wrong repo. If you can help move it, I'd appreciate it 🙏

**Comment by dd32** [comment]
Should the Section remain named as `My Favourites` on the homepage and section header? It's just the Navigation that should have lower-case correct? ( This probably needs translation context, `_x( 'My favorites', 'navigation menu', 'wporg-plugins' )` to differentiate it.)

| [Homepage](https://wordpress.org/plugins/#:~:text=Tested%20with%206.5.3-,My%20Favorites,-See%20all ) | [Header](https://wordpress.org/plugins/browse/favorites/#:~:text=Search%20plugins-,My%20Favorites,-The%20below%20plugins) |
| --- | --- |
| <img width="658" alt="Screenshot 2024-05-15 at 1 20 18 PM" src="https://github.com/WordPress/wordpress.org/assets/767313/07c91c03-307c-481a-8418-4074f952f6ee"> |  <img width="865" alt="Screenshot 2024-05-15 at 1 21 12 PM" src="https://github.com/WordPress/wordpress.org/assets/767313/ea4b3428-19cc-4b52-9171-9e79d0b8b48d"> |

**Comment by jasmussen** [comment]
Ideally we unify our use of sentence case, OR title case, for menu items and headings, across the entire site and all contexts. I lean towards sentence case, as that appears to be used the most, but really it's about the consistency. Most near term, however, it's just important to unify the menu item so it's the same across plugin, pattern and theme directories.

**Comment by ryelle** [comment]
We have already decided that we're unifying on sentence case, so yes, I'd update that on these headings as well.
