### ISSUE TITLE
Plugins: excerpt with new lines break card height

### ISSUE THREAD

**Issue by pkevan** [WordPress/wordpress.org#325]
Plugins with excerpts that contain line breaks alter the overall height of all plugin cards.

Ideally we would either trim the line breaks, or force the height of all cards to not be affected by a single card being larger - unsure which is the preferred path here.

Is there a use-case for having spaces in the excerpt?

![Screenshot 2024-06-06 at 09 52 48](https://github.com/WordPress/wordpress.org/assets/2290623/c5bb1c5f-ccc1-4a09-8d18-11fd6a29760a)
Example breakage: https://wordpress.org/plugins/search/wallet-login/

See: https://wordpress.slack.com/archives/C02QB8GMM/p1717656589572789

**Comment by adamwoodnz** [comment]
I vote for trimming the line breaks, can't see how that could ever be a desirable layout for that text content.
