### ISSUE TITLE
Forums: Search should not return matches from navigation links

### ISSUE THREAD

**Issue by obulat** [WordPress/wordpress.org#352]
When I search the support forums for "Openverse" and sort by date, I get _all_ forum pages:

<img width="500" alt="Search results for Openverse in WordPress support forums" src="https://github.com/user-attachments/assets/681d3fce-5c9c-4a36-b701-9744d82cfb18">

It seems that the whole forum page including the navigation links (with Openverse in them) is indexed for search. This should be updated to only index the forum posts and replies.

**Comment by dd32** [comment]
As this is powered by Google Search, it's not possible to exclude specific parts of the page.

This will be able to be resolved by removing Google Search: https://meta.trac.wordpress.org/ticket/3388
