### ISSUE TITLE
Plugins: Wrong textdomain for front page tagline

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordpress.org#353]
The dynamic tagline "Extend your WordPress experience! Browse over %s free plugins." was added in #321, but uses the wrong textdomain. This is causing the string to not be translated. It should be `wporg-plugins`.

**Comment by nguyenquanghoang** [comment]
Thank you for sending this error, This is also my problem when translating to Vietnamese but not displayed. Then I checked and it is a common problem, not just Vietnamese. 🙏
