### ISSUE TITLE
Customizer | links with autofocus parameter stopped working

### ISSUE THREAD

**Issue by ChrisPlaneta** [WordPress/wordpress.org#355]
URLs with autofocus parameter no longer work in customizer. For example, the link below should open Custom CSS section in the customzier, but it does not.

`https://example.com/wp-admin/customize.php?autofocus[panel]=custom_css`

I checked it on the latest version of WP, with all plugins disabled and with the default theme, GenerateBlocks, Kadence and Blocksy.

**Comment by pkevan** [comment]
hi @ChrisPlaneta - this repo is for the sites running on wordpress.org, rather than WordPress software itself.

You'll want to report that over on core.trac.wordpress.org.

Thanks!
