### ISSUE TITLE
WordPress core PHP 8.3 compatibility: When out of BETA?

### ISSUE THREAD

**Issue by awebguy99** [WordPress/wordpress.org#359]
From what I can see, WordPress core still doesn't officially support PHP 8.3.
The last update I've found shows it's still in BETA;
(But please add a comment if you've found a more recent update saying it's now supported)

https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/

Does anyone know what is preventing PHP 8.3 from coming out of BETA support to being officially supported?
Are they waiting for most/all plugins to declare compatibility first?

**Comment by dd32** [comment]
Hi @awebguy99,

You've found the GitHub repository for reporting issues on the WordPress.org site, please note that we're not the team actively working on WordPress Core, nor the PHP Compatibility subteam of the Core team.

That being said:

The WordPress Core team has an open ticket detailing what's required in their opinion to mark PHP 8.3 support as being "out of beta":
https://core.trac.wordpress.org/ticket/59231

There are also a number of other related tickets marked as being related to PHP 8.3:
https://core.trac.wordpress.org/query?status=!closed&keywords=~php83

It appears that this post on the Core teams p2 covers what is required before marking it as not-beta:
https://make.wordpress.org/core/2023/06/20/proposal-criteria-for-removing-beta-support-from-each-php-8-version/

The WordPress team uses Slack for realtime communication, you can find the group mostly resposible for PHP compatibility in the #core-php channel. For details on slack, please see: https://make.wordpress.org/chat/

> Are they waiting for most/all plugins to declare compatibility first?

No, plugins/themes are able to declare their compatibility separately, this is not actively taken into consideration by the Core Team as part of the decision AFAIK.

I'm marking this issue as closed/not-planned as it's unrelated to the WordPress.org website itself, but please note that you can still respond to it.
