### ISSUE TITLE
Make blog pinned post style

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#366]
The pinned post style needs an update, current style with new theme activated:

<img src="https://github.com/user-attachments/assets/3ccf9643-f69a-430f-a88b-2aa74c0bf724" width="600">

**Comment by adamwoodnz** [comment]
@WordPress/meta-design

**Comment by jasmussen** [comment]
How about this?
![Screenshot 2024-09-10 at 10 15 26](https://github.com/user-attachments/assets/73987382-c3f8-431c-b980-d3e6a379a96f)

CSS:

```

/* Pinned posts */
.post.sticky .o2-post {
    border-top: none;
    background: var(--wp--preset--color--blueberry-4);
    padding-top: 40px !important;
    margin-top: 40px;
}

.sticky .o2-post:after {
    top: 44px;
    right: 60px;
    font-size: 14px;
    padding: 4px;
    background: var(--wp--preset--color--blueberry-1);
    border-radius: 2px;
    line-height: 14px;
}
```
