### ISSUE TITLE
Automatic package releases are not working on past branches

### ISSUE THREAD

**Issue by nukaga** [WordPress/wordpress.org#372]
It seems that some security updates and other releases are not being automatically released on past branches for each language version.

![Frame 1](https://github.com/user-attachments/assets/f548fda8-391d-4530-a547-8c820bf4f9ad)
https://wordpress.org/download/releases/#branch-58
https://ja.wordpress.org/download/releases/#branch-58
https://ru.wordpress.org/download/releases/#branch-58

For example, the latest version of 5.8 Branch is 5.8.10, released on June 24, 2024, but it has not been released in the Japanese or Russian versions.

The versions of each language version that were not released that tenpra-san found on September 19th are as follows.

> These are the latest versions of past branches.
> 6.1.7
> 6.0.9
> 5.9.10
> 5.8.10
> 5.7.12
> 5.6.14
> 5.5.15
> 5.4.16
> 5.3.18
> 5.2.21
> 5.1.19
> 5.0.22
> 4.9.26
> 4.8.25
> 4.7.29
> 4.6.29
> 4.5.32
> 4.4.33
> 4.3.34
> 4.2.38
> 4.1.41
> I have only checked ja, ru, and en-gb yet, but unfortunately none of the locales have been able to automatically release the latest versions of these. This is somewhat different from what 
> [@ocean90](https://wordpress.slack.com/team/U02RPUBET)
>  explained to us, since ja and en-gb do not ship custom files with their releases.

(Only the Japanese version was manually released at 4.9.26.)

This exchange is taking place on the #polygrots channel.
https://wordpress.slack.com/archives/C02RP50LK/p1726619245448409?thread_ts=1726618009.456989&cid=C02RP50LK

I would like to request the automatic release of the missing version, but how should I do that?

**Comment by Zodiac1978** [comment]
Some more context, especially discussions in Slack:

One of the first reports (including confusing answers):
https://wordpress.slack.com/archives/C02RQC6RW/p1720076757960659

Explanation by @ocean90 
> Release packages for locales that have customizations cannot currently be built automatically. There is a pending systems request to clean up the build server. As soon as this is done, packaging should be resuming. No ETA.
https://wordpress.slack.com/archives/C02RP50LK/p1721217473660349

Follow-up:
https://wordpress.slack.com/archives/C02RP50LK/p1721287671070769

5.9.10 still missing in DE AT
https://de-at.wordpress.org/download/releases/#branch-59

Available here:
https://wordpress.org/download/releases/#branch-59

Same for 5.8.10, 5.7.12, 5.6.14, 5.5.15, 5.4.16, 5.3.18, 5.2.21 and 5.1.19

The releases for DE AT stop here

The same problem is in on https://de.wordpress.org/download/releases/ and many more locales.

**Comment by ocean90** [comment]
The issue was fixed a few days ago.

**Comment by nukaga** [comment]
@ocean90 Thank you so much!

**Comment by Zodiac1978** [comment]
It was reported two months ago, the report was questioned by Dion and you give no further explanation what happened and why it lasted so long to fix it. 

My trust in the whole system WP.org is gone in the last weeks.
