### ISSUE TITLE
Make blogs: Convert callout blocks to notice blocks

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#374]
The Make blogs have old style callout blocks:

<img src="https://github.com/user-attachments/assets/82280567-9df7-4399-a604-590ddf0818fa" width="300">

These need to display as notice blocks. We added a [mu-plugin to convert callout shortcodes to notices](https://github.com/WordPress/wporg-mu-plugins/pull/337), perhaps we can use a similar approach, or failing that, add these [fallback styles](https://github.com/WordPress/wporg-developer/pull/429) to the parent theme.

This should also address the [styles of the callout blocks on Learn](https://github.com/WordPress/Learn/issues/2739#issuecomment-2272886063).

**Comment by jonathanbossenger** [comment]
Adding an example lesson using old callouts for testing: https://learn.wordpress.org/lesson/how-classic-and-block-themes-are-developed/

**Comment by adamwoodnz** [comment]
> Adding an example lesson using old callouts for testing: https://learn.wordpress.org/lesson/how-classic-and-block-themes-are-developed/

Sorry, but I can't see any callouts in that lesson, has it been updated?

**Comment by adamwoodnz** [comment]
> > Adding an example lesson using old callouts for testing: https://learn.wordpress.org/lesson/how-classic-and-block-themes-are-developed/
> 
> Sorry, but I can't see any callouts in that lesson, has it been updated?

Ignore me, I just couldn't see them because of the broken styling. Here's what they look like once converted to notice via the mu-plugins change:

![Image](https://github.com/user-attachments/assets/ee1a44d5-9116-45ec-be01-50dd87f8ba62)

I'm not quite sure why the callout blocks are completely broken now, it looks like they can't even be inserted anymore... investigating.

**Comment by adamwoodnz** [comment]
> I'm not quite sure why the callout blocks are completely broken now, it looks like they can't even be inserted anymore... investigating.

Discovered that callout blocks are part of the Handbook plugin, so they broke when we deactivated it.

**Comment by adamwoodnz** [comment]
Closed by https://github.com/WordPress/wporg-mu-plugins/pull/660

**Comment by adamwoodnz** [comment]
Still issues with o2, now causing recursive loops and timeouts
