### ISSUE TITLE
Plugins: Button sizes have gotten smaller

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#375]
It seems like the button sizes fro Download and Live Preview have gotten smaller recently. They should be the same height as the Favorites button. 

<img width="470" alt="image" src="https://github.com/user-attachments/assets/467de8ff-feba-46df-a812-8c58addaa586">

**Comment by ryelle** [comment]
This has already been reported: https://github.com/WordPress/wporg-parent-2021/issues/157 (someone had been working on it on WCUS contributor day, but I don't think they finished).
