### ISSUE TITLE
Page headers could be more substantial

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wordpress.org#389]
Here’s what they look like at the moment:

![Image](https://github.com/user-attachments/assets/a2029eb3-da0b-4404-8bab-974932a444c6)

A few suggestions:

* If possible, we should fix the heading level violation by changing the page title to an h1. It’s an h2 at the moment.
* The sizes can also use an update, so in this case the h1 is larger than the h2.
* If we can tweak the lineheight too, so it lines up with the … ellipsis icon, that would be good.

**Comment by adamwoodnz** [comment]
What do you think of using Garamond for page titles, like other sites?

![Image](https://github.com/user-attachments/assets/896cb156-47cd-43c2-8b19-64dba690bd06)

![Image](https://github.com/user-attachments/assets/17c29c79-c1ec-4008-b1db-b5e62cc7040b)

![Image](https://github.com/user-attachments/assets/0a8b2520-8c03-4bdb-afe3-bf127761744b)

**Comment by adamwoodnz** [comment]
Regarding the title using an h2, it will require an o2 plugin change, but I think that's doable.

**Comment by jasmussen** [comment]
I think we should probably keep using Inter for the headings. And so if the main headings are heading level 3 at the moment, then heading level 2 size could be used for the "parent". That's only 32px and 29px, so not a huge differential, might even want to use heading level 1 size for the ancestor, but for this update, it may be fine.
