### ISSUE TITLE
class-wp-list-table.php

### ISSUE THREAD

**Issue by LucLaverdure** [WordPress/wordpress.org#392]
Fatal error on line 1039 on WPML 4.6.13 Updates and PHP version 8.3:

before:
```
$output = '<span class="displaying-num">' . sprintf(
/* translators: %s: Number of items. */
_n( '%s item', '%s items', $total_items ),
number_format_i18n( $total_items )
) . '</span>';

Uncaught ValueError: Unknown format specifier "a"
```
fix:
```
$total_items = isset($this->_pagination_args['total_items']) ? intval($this->_pagination_args['total_items']) : 0;

$output = '<span class="displaying-num">' . sprintf(
    /* translators: %s: Number of items. */
    _n( '%s item', '%s items', $total_items, 'text-domain' ), /* I assume the error is here with no domain being set */
    number_format_i18n( $total_items )
) . '</span>';
```

**Comment by dd32** [comment]
Hi @LucLaverdure,

You've found a place to report issues on WordPress.org, but not issues within plugins or Core.

The fix appears to imply that the WPML plugins is failing to pass a required parameter to the pagination functions, this should be reported to their developers.

If you feel that this is a Core WordPress issue, this should be reported via https://core.trac.wordpress.org/newticket

I'm closing this ticket, as this is unrelated to this GitHub repository, and WordPress does not have any GitHub repositories to report core issues.
