### ISSUE TITLE
Update Make/Chat design

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#398]
https://make.wordpress.org/chat/ currently uses the Twenty Twelve theme, with light styling via customizer. As part of the Make redesign we could load the [parent theme](https://github.com/wordpress/wporg-parent-2021) and use the site editor to customize.

The aim of this would be to simply modernize and align the design with other WordPress.org subsites, rather than an evolution of the page.

**Comment by fcoveram** [comment]
This page looks in a silo without the global header and local nav. I would add both components and a link in local nav that takes to this page in addition to the theme update.

**Comment by adamwoodnz** [comment]
Noting that the video will be outdated when we launch the new Make theme

![Image](https://github.com/user-attachments/assets/7235cca0-ee80-478f-9d7a-07a76230888a)

**Comment by adamwoodnz** [comment]
Just had a thought, should the local nav link be 'Slack' or 'Chat'? The focus of the page is definitely Slack, but the site title is Chat.

**Comment by fcoveram** [comment]
I don't like neither 😅 "Slack" is the platform used by says nothing about the communication purpose, while "Chat" feels outdated. Pinging @bjmcsherry asking for suggestions. Otherwise, we can continue with "Chat" and revisit it in the future

**Comment by adamwoodnz** [comment]
How about 'Collaborate', 'Collaboration', 'Communicate', 'Communication'?

**Comment by fcoveram** [comment]
"Communicate" sounds good ✨
