### ISSUE TITLE
Update sidebar icons.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#404]
Can we update the icons for these links in the sidebar?

- Recent Updates
- Recent Comments
- My @Mentions
- No Replies
- My Posts

![Image](https://github.com/user-attachments/assets/9b576646-a5c1-4e8a-93b4-8c1601a175a2)

**Comment by adamwoodnz** [comment]
@WordPress/meta-design want to do anything here?

**Comment by jasmussen** [comment]
Yes, the icons should either be updated withi counterparts from [WordPress Icons](https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library)—there should be one for each. Or, we can justremove them. It's not clear they add a ton of value. I'd support either.

**Comment by adamwoodnz** [comment]
How's this?

![Image](https://github.com/user-attachments/assets/e8d84c28-36c7-48b0-8dcb-820624df3c12)

The latest activity list may not always be displayed below it, but I've aligned the icons and text with that.

**Comment by jasmussen** [comment]
Can work! Though honestly I think I'd personally prefer not showing icons there. They aren't really adding a whole ton of value compared to the text labels. Thanks for exploring.

While I remember: can we/have we added `text-wrap: pretty;` across this make section? Hoping it's already there, globally across the site, just making sure!

**Comment by adamwoodnz** [comment]
> can we/have we added `text-wrap: pretty;` across this make section?

Confirming this rule is in place across the site (and applied in the sidebar):

```
--wp--custom--body--typography--text-wrap: pretty;

p, ul, ol, blockquote {
    text-wrap: var(--wp--custom--body--typography--text-wrap);
}
```
