### ISSUE TITLE
Hovering over a meta ticket does something weird.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#411]
This pre-dates the redesign, but when you hover over a meta ticket, you get a weird box.

## Screenshot
![Image](https://github.com/user-attachments/assets/76cc8730-61b0-49b4-8b77-a46f1b61a35d)

## Steps to reproduce
1. See https://make.wordpress.org/meta/2024/10/02/agenda-for-october-1-2024
2. Find [Ticket #7763](https://meta.trac.wordpress.org/ticket/7763)
3. Hover over it.

**Comment by ryelle** [comment]
That should be showing a ticket or changeset preview, like this from make/core. Looks like it isn't working for meta.trac?

![Image](https://github.com/user-attachments/assets/19ed7870-e25f-4c36-addc-9d8afbffd23a)

**Comment by adamwoodnz** [comment]
Found the code at `make-network/p2-hovercards`, but haven't debugged yet

**Comment by adamwoodnz** [comment]
Turns out this was just an incorrectly formatted link. Changing `Ticket #7763` to `#7763` fixed it

![Image](https://github.com/user-attachments/assets/0fc16a6b-ce72-41e4-a788-e01d65578d0c)

fyi @courtneyr-dev
