### ISSUE TITLE
Faint white border on "Edit" tab.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#412]
There is a white border on `o2-editor-tabs .selected` that make the tabs look weird.

## Screenshot

![Image](https://github.com/user-attachments/assets/b5624d14-ee4f-4d99-a228-7bd91ab00e1b)

**Comment by fcoveram** [comment]
The work made in [wporg-photo-directory/PR#13](https://github.com/WordPress/wporg-photo-directory/pull/13) seems perfect for this issue.
