### ISSUE TITLE
Bug in Footer Plugin Changeset Trac

### ISSUE THREAD

**Issue by BenjaminZekavica** [WordPress/wordpress.org#418]
Currently is the footer crashed on the Changeset Trac: 
For example: https://plugins.trac.wordpress.org/changeset/3181757

We need a fix for the WP.org Footer

![Image](https://github.com/user-attachments/assets/181397ab-6f27-4f6f-8589-d63366a2e1c7)

**Comment by dd32** [comment]
This is a known issue: https://meta.trac.wordpress.org/ticket/6370
