### ISSUE TITLE
Apply "pretty" text wrap on profile pages, at least the author bios

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wordpress.org#419]
The CSS `text-wrap: pretty;` should already be applied across most of the website, and when applied it avoids typographic widows in text. It's missing on the profile page ([example](https://profiles.wordpress.org/joen/)):

![Image](https://github.com/user-attachments/assets/e71bdc65-04cd-4ade-975b-6da36ae6a53f)

It would be good to add there.

**Comment by jasmussen** [comment]
Feel free to move this issue if I created it in the wrong repository!

**Comment by StevenDufresne** [comment]
Updated. Thanks!
