### ISSUE TITLE
JS bug in o2 notifications script

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#439]
There is a bug in the notifications script on o2 blog pages like https://make.wordpress.org/core/

Doesn't seem to affect functionality.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'open')
    at HTMLDocument.<anonymous> (notifications.js?ver=6.8-alpha-59504:80:19)
    at HTMLDocument.dispatch (jquery.min.js?ver=3.7.1:2:40035)
```

**Comment by adamwoodnz** [comment]
Needs to be transferred to the o2 repo

**Comment by dd32** [comment]
Upstream issue: https://github.com/Automattic/o2/issues/225
