### ISSUE TITLE
Make : sub section navigation

### ISSUE THREAD

**Issue by addedlovely** [WordPress/wordpress.org#447]
Once you are in a subsection on the 'make' site, there isn't a simple way to return to the top level 'make' page. 

It appears to only be accessible via the main navigation, under 'Community' > 'Make WordPress'.

Could the top level 'Make WordPress Core' label, be changed to a breadcrumb with two links 'Make WordPress' > 'Core', example attached.

<img width="1904" alt="Image" src="https://github.com/user-attachments/assets/012f19e6-bb10-4cdd-b9b6-ab428dd9fba1" />

**Comment by adamwoodnz** [comment]
This has been discussed in #405 and it was decided that it isn't required.

**Comment by addedlovely** [comment]
@adamwoodnz ok. Just seems inconsistent with every other refreshed section, where that link remains the parent section you are in, and let's you get back to the top level e.g.

Showcase 
https://wordpress.org/showcase/category/community/

News
https://wordpress.org/news/category/testing/

About
https://wordpress.org/about/license/
