### ISSUE TITLE
Pre submit comment

### ISSUE THREAD

**Issue by Pizza1** [WordPress/wordpress.org#449]
Hi,

Is there a way to hook into pre submit of a comment (before it saves the comment) as to block comment submit if a certain condition is met?

Thanks

**Comment by dd32** [comment]
Hello @Pizza1,

This repository is for development of the WordPress.org website itself, and is not for support requests or Developer support.

You may find something by looking at the [wp_handle_comment_submission()](https://developer.wordpress.org/reference/functions/wp_handle_comment_submission/) documentation, looking at how similar plugins work, or the Developing with WordPress forum: https://wordpress.org/support/forum/wp-advanced/
